require("core.plugin-config.alpha")
require("core.plugin-config.mason")
require("core.plugin-config.languages")
require("core.plugin-config.lsp-config")
require("core.plugin-config.completions")
require("core.plugin-config.nvim-tree")
require("core.plugin-config.treesitter")
require("core.plugin-config.telescope")
require("core.plugin-config.lualine")
require("core.plugin-config.indent-blankline")
require("core.plugin-config.git-signs")
require("core.plugin-config.fterm")
require("core.plugin-config.guess-indent")
require("core.plugin-config.better-escape")
require("core.plugin-config.bufferline")
-- not needed: require("core.plugin-config.colorscheme")
-- not installed: require("core.plugin_config.vim-test")
-- not installed: require("core.plugin_config.copilot")
-- not installed: require("core.plugin-config.dap-config")